### ISSUE TITLE
Error Get QRcode

### ISSUE THREAD

**Issue by ardesign91** [edupoli/MyZap2.0#2]
Para obter QRcode sempre erro no carteiro.
<script>

var settings = {
  "url": "http://localhost:3333/getQrCode?session=session&sessionkey=12",
  "method": "GET",
  "timeout": 0,
};

$.ajax(settings).done(function (response) {
  console.log(response);
});

</script>

{
    "error": "Sessão não informada."
}

**Comment by edupoli** [comment]
Corrigido o problema
